"""add order filed to Option table

Revision ID: 054e6c9fe50a
Revises: 1ee01fa98411
Create Date: 2024-05-16 18:19:23.639528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '054e6c9fe50a'
down_revision: Union[str, None] = '1ee01fa98411'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('options', sa.Column('order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('options', 'order')
    # ### end Alembic commands ###
