"""create user survey table

Revision ID: 1ee01fa98411
Revises: 8bd0f6bb0ad3
Create Date: 2024-05-15 17:33:10.371486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1ee01fa98411'
down_revision: Union[str, None] = '8bd0f6bb0ad3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('survey_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('options',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('survey_question_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['survey_question_id'], ['survey_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('survey_response',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['options.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('current_medicine',
    sa.Column('survey_response_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['survey_response_id'], ['survey_response.id'], ),
    sa.PrimaryKeyConstraint('survey_response_id')
    )
    op.create_table('past_medicine',
    sa.Column('survey_response_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['survey_response_id'], ['survey_response.id'], ),
    sa.PrimaryKeyConstraint('survey_response_id')
    )
    op.create_table('reason_medicine',
    sa.Column('survey_response_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['survey_response_id'], ['survey_response.id'], ),
    sa.PrimaryKeyConstraint('survey_response_id')
    )
    op.alter_column('users', 'user_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'provider',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'access_token',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'refresh_token',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'refresh_token',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'access_token',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'provider',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'user_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_table('reason_medicine')
    op.drop_table('past_medicine')
    op.drop_table('current_medicine')
    op.drop_table('survey_response')
    op.drop_table('options')
    op.drop_table('survey_questions')
    # ### end Alembic commands ###
