"""modify user table

Revision ID: 4c3be9dc3611
Revises: 85ebe9d082f7
Create Date: 2024-03-25 09:32:31.401088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4c3be9dc3611'
down_revision: Union[str, None] = '85ebe9d082f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_id', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('provider', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('access_token', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('refresh_token', sa.String(length=255), nullable=False))
    op.drop_column('users', 'naver_access_token')
    op.drop_column('users', 'kakao_id')
    op.drop_column('users', 'kakao_refresh_token')
    op.drop_column('users', 'kakao_access_token')
    op.drop_column('users', 'naver_id')
    op.drop_column('users', 'naver_refresh_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('naver_refresh_token', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('users', sa.Column('naver_id', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('users', sa.Column('kakao_access_token', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('users', sa.Column('kakao_refresh_token', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('users', sa.Column('kakao_id', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('users', sa.Column('naver_access_token', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('users', 'refresh_token')
    op.drop_column('users', 'access_token')
    op.drop_column('users', 'provider')
    op.drop_column('users', 'user_id')
    # ### end Alembic commands ###
