"""revision survey model

Revision ID: 69e9c5dc8c33
Revises: 664dc68d3bc2
Create Date: 2024-05-22 16:28:35.533859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '69e9c5dc8c33'
down_revision: Union[str, None] = '664dc68d3bc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surveys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_responses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('response', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['option_id'], ['options.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('reason_medicine')
    op.drop_table('past_medicine')
    op.drop_table('current_medicine')
    op.drop_table('survey_response')
    op.drop_table('survey_questions')
    op.add_column('options', sa.Column('question_id', sa.Integer(), nullable=False))
    op.add_column('options', sa.Column('next_question_id', sa.Integer(), nullable=True))
    op.drop_constraint('options_ibfk_1', 'options', type_='foreignkey')
    op.create_foreign_key(None, 'options', 'questions', ['next_question_id'], ['id'])
    op.create_foreign_key(None, 'options', 'questions', ['question_id'], ['id'])
    op.add_column('users', sa.Column('user_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('jwt_rfresh_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('tartget_weight', sa.Float(), nullable=True))
    op.drop_column('users', 'user_social_id')
    op.drop_column('users', 'target_weight')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('target_weight', mysql.FLOAT(), nullable=True))
    op.add_column('users', sa.Column('jwt_refresh_token', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('users', sa.Column('user_social_id', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('users', 'tartget_weight')
    op.drop_column('users', 'jwt_rfresh_token')
    op.drop_column('users', 'user_id')
    op.add_column('options', sa.Column('survey_question_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'options', type_='foreignkey')
    op.drop_constraint(None, 'options', type_='foreignkey')
    op.create_foreign_key('options_ibfk_1', 'options', 'survey_questions', ['survey_question_id'], ['id'])
    op.drop_column('options', 'next_question_id')
    op.drop_column('options', 'question_id')
    op.create_table('current_medicine',
    sa.Column('survey_response_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('frequency', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['survey_response_id'], ['survey_response.id'], name='current_medicine_ibfk_1'),
    sa.PrimaryKeyConstraint('survey_response_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('survey_questions',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('text', mysql.TEXT(), nullable=True),
    sa.Column('order', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('past_medicine',
    sa.Column('survey_response_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['survey_response_id'], ['survey_response.id'], name='past_medicine_ibfk_1'),
    sa.PrimaryKeyConstraint('survey_response_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('survey_response',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('option_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['options.id'], name='survey_response_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='survey_response_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('reason_medicine',
    sa.Column('survey_response_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reason', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['survey_response_id'], ['survey_response.id'], name='reason_medicine_ibfk_1'),
    sa.PrimaryKeyConstraint('survey_response_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('user_responses')
    op.drop_table('questions')
    op.drop_table('surveys')
    # ### end Alembic commands ###
