"""add naver_token

Revision ID: 85ebe9d082f7
Revises: 736b0a3be9b7
Create Date: 2024-03-25 09:20:03.473896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85ebe9d082f7'
down_revision: Union[str, None] = '736b0a3be9b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('naver_id', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('naver_access_token', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('naver_refresh_token', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'naver_refresh_token')
    op.drop_column('users', 'naver_access_token')
    op.drop_column('users', 'naver_id')
    # ### end Alembic commands ###
