"""2024.06.01 0815

Revision ID: e1dcfed7f2f1
Revises: c05c291cb882
Create Date: 2024-06-01 08:15:50.504181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e1dcfed7f2f1'
down_revision: Union[str, None] = 'c05c291cb882'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surveys', sa.Column('total_page', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surveys', 'total_page')
    # ### end Alembic commands ###
