"""modify column settings in User

Revision ID: f1fe74b10ff3
Revises: 43a4cb2c1e3a
Create Date: 2024-05-22 19:35:58.931919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f1fe74b10ff3'
down_revision: Union[str, None] = '43a4cb2c1e3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'jwt_refresh_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('jwt_refresh_token', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
