"""20240702 2036

Revision ID: f72413bfeb66
Revises: e1dcfed7f2f1
Create Date: 2024-07-02 20:37:24.826451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f72413bfeb66'
down_revision: Union[str, None] = 'e1dcfed7f2f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'access_token', new_column_name='social_access_token', existing_type=sa.String(length=255), existing_nullable=True)
    op.alter_column('users', 'refresh_token', new_column_name='social_refresh_token', existing_type=sa.String(length=255), existing_nullable=True)
    op.drop_column('users', 'jwt_refresh_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('jwt_refresh_token', mysql.VARCHAR(length=255), nullable=True))
    op.alter_column('users', 'social_access_token', new_column_name='access_token', existing_type=sa.String(length=255), existing_nullable=True)
    op.alter_column('users', 'social_refresh_token', new_column_name='refresh_token', existing_type=sa.String(length=255), existing_nullable=True)
    # ### end Alembic commands ###
