"""add blood_type field in User

Revision ID: fe3b835913f1
Revises: 4c3be9dc3611
Create Date: 2024-03-30 17:26:26.570568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe3b835913f1'
down_revision: Union[str, None] = '4c3be9dc3611'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('blood_type', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'blood_type')
    # ### end Alembic commands ###
