name: Build and Push Dev

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.0.0
      
    - name: Login to Dockerhub
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: build and push
      if: success()
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/foodteacher-be-dev:${{ github.sha }}
        
    - name: Update docker image name
      run: |
        git init
        git config --global user.email "gracehpark@naver.com"
        git config --global user.name "gracehpark0120"
        git clone https://${{ secrets.GIT_TOKEN }}@github.com/foodteacher/devops.git
        cd devops/be
        sed -i "s|gracehpark/foodteacher-be-dev:.*|gracehpark/foodteacher-be-dev:${{ github.sha }}|g" be-dev.yaml
        git commit -am "Update Docker Image Name"
        git push
    
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: 'The project {{ EVENT_PAYLOAD.repository.full_name }}-dev has been deployed.'
  
   
